### ISSUE TITLE
 Could you migrate railsgirls.com to HTTPS? (mixed http and https content)

### ISSUE THREAD

**Issue by emorima** [railsgirls/railsgirls.org#2093]
Hi,
Google Chrome 81 blocks mixed content.
Image src pathes of many coaches are https pathes.("twimg.com", "gravatar.com", "githubusercontent.com" and "githubusercontent.com")
So currently unable to display images of many coaches on event pages.

I want to migrate railsgirls.com to HTTPS and resolved mixed content, how about this?

**Comment by hsbt** [comment]
https://railsgirls.org/ is HTTPS.
